# Generated by Django 5.1.7 on 2025-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='unknown', help_text='Enter your full address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_donation_date',
            field=models.DateField(blank=True, help_text='Date of last blood donation', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
